# Enable stateless CSRF protection for forms and logins/logouts
framework:
    form:
        csrf_protection:
            enabled: '%env(bool:CSRF_ENABLED)%'
            token_id: submit

    csrf_protection:
        stateless_token_ids:
            - submit
            - authenticate
            - logout
